### ISSUE TITLE
I want to timestamp the coordinate results of DR and Map-Aided DR using the code.

### ISSUE THREAD

**Issue by Fullmoon34213** [anisghaoui/humolire#1]
Hello.  
First of all, thank you for providing the code and the paper.
I have conducted PDR (Pedestrian Dead Reckoning) using the provided code for test purpose and obtained meaningful results.
I would like to compare the coordinates obtained through DR with those corrected based on the Grid map at the same timestamps. 
Therefore, I would like to include timestamps for each coordinate in the code.
 From my analysis of the code, it seems that the coordinates obtained through DR are stored in pdr_positions in main.py(line 81), 
`pdr_positions, total_distance = compute_positions(*perform_pdr(acce, gyro, **kwargs)`
and the corrected coordinates based on the Grid map are likely to be found in plot_particles_center within visualize.py(line 121,122).
` X = [center.x for center in center_positions]
  Y = [center.y for center in center_positions]`
  My questions are as follows:
  1. Could you please provide a way to include timestamps for both DR coordinates and Grid map-based corrected coordinates?
  2. Alternatively, should I consider that the generated coordinates are estimated at 1-second intervals? I am asking this because there seems to be a parameter for steps per second.

Thank you for reading my message, and I would greatly appreciate your response as it would be immensely helpful to me. Thank you, and have a great day.

**Comment by anisghaoui** [comment]
Hello,
During each iteration, the PF computes the weighted average. The `center_life` contains these successive positions estimated by the PF. You want to compare those to the PDR estimated ones.
 
https://github.com/anisghaoui/humolire/blob/fd49117013f3167d8b95d9bc60946ad16d0e8aa3/humolire/main.py#L78 

The coordinates are generated when a step event occurs. The system is strictly event-driven (not time). So, the estimation is not periodical.

Have a nice day.

**Comment by Fullmoon34213** [comment]
Thank you for your kind response. I understood how it works and was able to achieve the results I wanted.
